# Generated by Django 3.0.2 on 2020-01-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(max_length=3000)),
                ('received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
