# Generated by Django 3.0.2 on 2020-01-22 12:36

import django.contrib.postgres.fields
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('about', 'about'), ('skills', 'skills'), ('work', 'work'), ('contact', 'contact')], max_length=1000)),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'about',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('section', models.CharField(choices=[('Language', 'Language'), ('Framework', 'Framework'), ('Backend', 'Backend')], max_length=10)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skilles',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('work', 'work'), ('project', 'project')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('img', models.URLField()),
                ('descripiton', markdownx.models.MarkdownxField()),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None), size=None)),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=350), size=None), size=None)),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'works',
            },
        ),
    ]
