# Generated by Django 3.0.2 on 2020-01-12 10:57

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skilles'},
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
