# Generated by Django 3.0.2 on 2020-01-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_auto_20200127_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='points',
        ),
    ]
